
development:
  adapter: postgresql
  encoding: unicode
  database: simple_task_manager_dev
  pool: 5
  username: sergey

test:
  adapter: postgresql
  encoding: unicode
  database: simple_task_manager_test
  username: postgres
